// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For Turso: embed the auth token in the URL so the Prisma CLI can connect
    url: process.env.TURSO_AUTH_TOKEN
      ? `${process.env.DATABASE_URL}?authToken=${process.env.TURSO_AUTH_TOKEN}`
      : process.env.DATABASE_URL,
  },
});
